//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BerconNoise.rc
//
#define IDS_LIBDESCRIPTION              1
#define IDS_CATEGORY                    2
#define IDS_CLASS_NAME                  3
#define IDS_PARAMS                      4
#define IDS_SPIN                        5
#define IDS_BERCON_WOOD                 5
#define IDS_WOODSIZE                    6
#define IDS_COORDS                      7
#define IDS_OUTPUT                      8
#define IDS_AGAMMA                      8
#define IDS_RADIAL_WOOD                 9
#define IDS_AHUE                        9
#define IDS_TILING                      10
#define IDS_TILINGSIZE                  11
#define IDS_RGAMMA                      11
#define IDS_DISTORTION_STRENGTH         12
#define IDS_RHUE                        12
#define IDS_DISTORTION_MAP              13
#define IDS_RSAT                        13
#define IDS_NF_WORLEY                   14
#define IDS_OGAMMA                      14
#define IDS_F_FRACTAL                   15
#define IDS_OHUE                        15
#define IDS_F_REGULAR                   16
#define IDS_OSAT                        16
#define IDS_F_TURBULENCE                17
#define IDS_RNDBY                       17
#define IDS_F_fBm                       18
#define IDS_F_FBM                       18
#define IDS_F_HETEROTERRAIN             19
#define IDS_BLUR                        19
#define IDS_F_HYBRIDMULTIFRACTAL        20
#define IDS_FILTERING                   20
#define IDS_F_RIDGEDMULTIFRACTAL        21
#define IDS_FRACTAL_GAIN                22
#define IDS_FRACTAL_OFFSET              23
#define IDS_FRACTAL_LACUNARITY          24
#define IDS_PERLIN_WOOD                 25
#define IDS_FRACTAL_H                   26
#define IDS_W_MI5                       27
#define IDS_W_MI4                       28
#define IDS_WOOD_TYPE                   29
#define IDS_TRUNKSTR                    30
#define IDS_TRUNKFREQ                   31
#define IDS_RADIALSTR                   32
#define IDS_RADIALFREQ                  33
#define IDS_WIDTHVAR                    34
#define IDS_SKEW                        35
#define IDS_ANGLESTR                    36
#define IDS_ANGLEFREQ                   37
#define IDS_DISTORTION_MAP2             38
#define IDS_USE_DISTORTION              39
#define IDS_SIMPLEX_WOOD                40
#define IDS_DS_COLOR3                   41
#define IDS_JW_MAP3                     42
#define IDS_JW_MAP3ENABLE               43
#define IDS_RADIALZ                     44
#define IDS_ANGLERAD                    45
#define IDS_LOCK_GRAIN                  46
#define IDS_GRAINSTR                    47
#define IDS_GRAINFREQ                   48
#define IDS_GAINVAR                     49
#define IDS_SEED                        50
#define IDS_CURVE                       51
#define IDS_BERCON_TILE                 52
#define IDS_TILETYPE_0                  53
#define IDS_TILETYPE_1                  54
#define IDS_TILETYPE_2                  55
#define IDS_TILETYPE_3                  56
#define IDS_TILETYPE_4                  57
#define IDS_TILETYPE_5                  58
#define IDS_TILETYPE_6                  59
#define IDS_TILETYPE_7                  60
#define IDS_TILETYPE_8                  61
#define IDS_TILESOFTEN_0                62
#define IDS_TILESOFTEN_1                63
#define IDS_TILESOFTEN_2                64
#define IDS_TILESOFTEN_3                65
#define IDS_CURVEPB                     66
#define IDS_CURVEPARM                   67
#define IDS_TILEROT_0                   68
#define IDS_TILEROT_1                   69
#define IDS_TILEROT_2                   70
#define IDS_TILEROT_3                   71
#define IDS_PBMAP                       72
#define IDS_MAP1                        73
#define IDS_MAP2                        74
#define IDS_MAP3                        75
#define IDS_MAP4                        76
#define IDS_MAP5                        77
#define IDS_MAP6                        78
#define IDS_MAP7                        79
#define IDS_MAP8                        80
#define IDS_MAP9                        81
#define IDS_MAP10                       82
#define IDS_MAP11                       83
#define IDS_MAP12                       84
#define IDS_MAP13                       85
#define IDS_MAP14                       86
#define IDS_MAP15                       87
#define IDS_MAP16                       88
#define IDS_MAPON1                      89
#define IDS_MAPON2                      90
#define IDS_MAPON3                      91
#define IDS_MAPON4                      92
#define IDS_MAPON5                      93
#define IDS_MAPON6                      94
#define IDS_MAPON7                      95
#define IDS_MAPON8                      96
#define IDS_MAPON9                      97
#define IDS_MAPON10                     98
#define IDS_MAPON11                     99
#define IDS_MAPON12                     100
#define IDD_PANEL                       101
#define IDS_MAPON13                     101
#define IDD_PANEL_WOOD                  102
#define IDS_MAPON14                     102
#define IDD_PANEL_TILE                  103
#define IDS_MAPON15                     103
#define IDB_BITMAPLOGO                  103
#define IDD_PANEL_CURVE                 104
#define IDS_MAPON16                     104
#define IDD_PANEL_WOOD_MAP              105
#define IDS_BERCON_DIST                 105
#define IDD_PANEL_DISTORTION            106
#define IDS_VAR_MAP                     106
#define IDS_VAR_TYPE                    107
#define IDD_PANEL_TILE_MAP              107
#define IDS_TILEVAR_0                   108
#define IDD_PANEL_NOISE_MAP             108
#define IDS_TILEVAR_1                   109
#define IDD_PANEL_COLOR                 109
#define IDS_TILEVAR_2                   110
#define IDD_PANEL_TILE1                 110
#define IDS_VAR_STR                     111
#define IDD_PANEL_TILE2                 111
#define IDS_UV_MAP                      112
#define IDD_XYZ                         112
#define IDS_TILEROT_4                   113
#define IDD_PANEL_TILE3                 113
#define IDS_W_ID                        114
#define IDD_PANEL_MULTI                 114
#define IDS_NF_BLENDER                  115
#define IDS_TILEUVW_0                   115
#define IDS_NF_CELL                     116
#define IDS_TILEUVW_1                   116
#define IDS_WORLEY_F1                   117
#define IDS_WORLEY_F2                   118
#define IDS_WORLEY_F3                   119
#define IDS_WORLEY_F4                   120
#define IDC_WORLEY_SOLID                121
#define IDS_TILE_SIZE                   122
#define IDS_TILE_STYLE                  123
#define IDS_TILE_WIDTH                  124
#define IDS_TILE_HEIGHT                 125
#define IDS_TILE_EWIDTH                 126
#define IDS_TILE_EHEIGHT                127
#define IDS_TILE_PERIOD                 128
#define IDS_TILE_OFFSET                 129
#define IDS_TILE_OFFSET2                130
#define IDS_TILE_SOFTEN                 131
#define IDS_TILE_SOFTRAD                132
#define IDS_TILE_ROUND                  133
#define IDS_TILE_ROUNDRAD               134
#define IDS_TILE_LOCK                   135
#define IDS_TILE_MAPUV                  136
#define IDS_TILE_ROTUV                  137
#define IDS_DIST_UVW                    138
#define IDS_UVW_NORMAL                  139
#define IDS_UVW_RADIAL                  140
#define IDS_UVW_SPHERICAL               141
#define IDS_TILETYPE_9                  142
#define IDS_F_FBMTURB                   143
#define IDS_LINEAR_WOOD                 144
#define IDS_BERCON_COLOR                145
#define IDS_SUBMAPS                     146
#define IDS_GRADTYPE_RANDOM             147
#define IDS_GRADTYPE_AGE                148
#define IDS_GRADTYPE_SPEED              149
#define IDS_GRADTYPE_SIZE               150
#define IDS_GRADINT_LINEAR              151
#define IDS_GRADINT_SMOOTH              152
#define IDS_GRADINT_SOLIDNEAR           153
#define IDS_GRADINT_SOLIDLEFT           154
#define IDS_GRADINT_SOLIDRIGHT          155
#define IDS_SUBCOLORS                   156
#define IDS_SUBPOSITIONS                157
#define IDS_KEYTEX                      158
#define IDS_KEYNUM                      159
#define IDS_KEYPOS                      160
#define IDS_KEYCOL                      161
#define IDS_GRADIENTTYPE                162
#define IDS_GRADIENTINTERPOLATION       163
#define IDS_RANDBYMAT                   164
#define IDS_RANDBYOBJ                   165
#define IDS_RANDBYPAR                   166
#define IDS_RANGEMIN                    167
#define IDS_RANGEMAX                    168
#define IDS_GRADTYPE_UVW                169
#define IDR_GRADIENTMENU                169
#define IDS_GRADTYPE_LIGHT              170
#define IDS_GRADTYPE_MAP                171
#define IDS_GRADTYPE_NORMAL             172
#define IDS_GRADTYPE_DISTANCE           173
#define IDS_GRADUVW_LINEAR              174
#define IDS_GRADUVW_RADIAL              175
#define IDS_GRADUVW_RECTANGLE           176
#define IDS_GRADUVW_DIAGONAL            177
#define IDS_GRADUVW_SPIRAL              178
#define IDS_GRADUVW_SWEEP               179
#define IDS_GRADUVW_TARTAN              180
#define IDS_GRADUVW_SPHERICAL           181
#define IDS_GRADUVW_BOX                 182
#define IDS_GRADUVW_PONG                183
#define IDS_LOOP_STRETCH                184
#define IDS_LOOP_TILE                   185
#define IDS_LOOP_MIRROR                 186
#define IDS_LOOP_NONE                   187
#define IDS_NORMAL_VIEW                 188
#define IDS_NORMAL_LOCALX               189
#define IDS_NORMAL_LOCALY               190
#define IDS_NORMAL_LOCALZ               191
#define IDS_NORMAL_WORLDX               192
#define IDS_NORMAL_WORLDY               193
#define IDS_NORMAL_WORLDZ               194
#define IDS_NORMAL_CAMERAX              195
#define IDS_NORMAL_CAMERAY              196
#define IDS_NORMAL_CAMERAZ              197
#define IDS_NORMAL_TOOBJECT             198
#define IDS_NORMAL_OBJECTZ              199
#define IDS_NORMAL_PARALLEL             200
#define IDS_NORMAL_TOWARDS              201
#define IDS_NORMAL_FRESNEL              202
#define IDS_MAP                         203
#define IDS_NODE                        204
#define IDS_REVERSE                     205
#define IDS_RANGELOOP                   206
#define IDS_GRADIENTUVW                 207
#define IDS_NORMALTYPE                  208
#define IDS_NORMALFUNCTION              209
#define IDS_IOR                         210
#define IDS_DISTON                      211
#define IDS_ULOOP                       212
#define IDS_VLOOP                       213
#define IDS_WLOOP                       214
#define IDS_SAMPLES                     215
#define IDS_XYZ                         216
#define IDS_XYZ_UVW                     217
#define IDS_XYZ_OBJ                     218
#define IDS_XYZ_WOR                     219
#define IDS_XYZ_SCR                     220
#define IDS_LOOP_CONT                   221
#define IDS_XYZ_UVW2                    222
#define IDS_NF_SIMPLEX3                 223
#define IDS_NF_SIMPLEX4                 224
#define IDS_NF_PERLIN2                  225
#define IDS_NF_PERLIN3                  226
#define IDS_NF_PERLIN4                  227
#define IDS_TILEUVW_2                   228
#define IDS_TILEUVW_3                   229
#define IDS_TILEUVW_4                   230
#define IDS_TILEUVW_5                   231
#define IDS_TILETYPE_10                 232
#define IDS_TILETYPE_11                 233
#define IDS_TILE_WIDTH2                 234
#define IDS_TILE_HEIGHT2                235
#define IDS_TILE_EWIDTH2                236
#define IDS_TILE_EHEIGHT2               237
#define IDS_TILE_AUTO                   238
#define IDS_UVWCHAN                     239
#define IDS_UVWCHAN2                    240
#define IDS_RANDOM_X_OFF                241
#define IDS_RANDOM_Y_OFF                242
#define IDS_RANDOM_X_SCA                243
#define IDS_RANDOM_Y_SCA                244
#define IDS_TILE_ROT                    245
#define IDS_FLIP_X                      246
#define IDS_FLIP_Y                      247
#define IDS_SUPPORT                     248
#define IDS_CENTER_MAP                  249
#define IDS_LOCK_SCALE                  250
#define IDS_PATTERN_STRING              251
#define IDS_CLASS_NAME_MULTI            252
#define IDS_AGAMMA2                     253
#define IDS_AHUE2                       254
#define IDS_RGAMMA2                     255
#define IDS_RHUE2                       256
#define IDS_RSAT2                       257
#define IDS_OGAMMA2                     258
#define IDS_OHUE2                       259
#define IDS_OSAT2                       260
#define IDS_RNDBY2                      261
#define IDS_STRING262                   262
#define IDS_BLUR2                       263
#define IDS_FILTERING2                  264
#define IDS_ASAT                        265
#define IDC_CLOSEBUTTON                 1000
#define IDC_DOSTUFF                     1000
#define IDC_OPENBUTTON                  1001
#define IDC_RNDBY_1                     1002
#define IDC_NOISE_FUNCTION              1003
#define IDC_RNDBY_2                     1003
#define IDC_WORLEY_DISTANCE             1004
#define IDC_FRACTAL_TYPE                1005
#define IDC_RELOADBUTTON                1005
#define IDC_FILTERING_1                 1006
#define IDC_DIST_UVW                    1007
#define IDC_LOGO                        1007
#define IDC_CURVE                       1008
#define IDC_FILTERING_2                 1008
#define IDC_TRUNKSTR_EDIT               1009
#define IDC_FILTERING_3                 1009
#define IDC_TRUNKSTR_SPIN               1010
#define IDC_RNDBY_3                     1010
#define IDC_TRUNKFREQ_EDIT              1011
#define IDC_TRUNKFREQ_SPIN              1012
#define IDC_WOODSIZE_EDIT               1013
#define IDC_WOODSIZE_SPIN               1014
#define IDC_SEED_EDIT                   1015
#define IDC_WOOD_TYPE                   1016
#define IDC_RANGEMIN_EDIT               1016
#define IDC_SEED_SPIN                   1017
#define IDC_TYPE                        1018
#define IDC_RANGEMAX_EDIT               1018
#define IDC_SOFTEN                      1019
#define IDC_IOR_EDIT                    1019
#define IDC_TILESIZE_EDIT               1020
#define IDC_DISTSTR_EDIT                1020
#define IDC_TILEWIDTH_EDIT              1021
#define IDC_TILESIZE_SPIN               1022
#define IDC_TILEWIDTH_SPIN              1023
#define IDC_TILEHEIGHT_EDIT             1024
#define IDC_TILEHEIGHT_SPIN             1025
#define IDC_EDGEWIDTH_EDIT              1026
#define IDC_EDGEWIDTH_SPIN              1027
#define IDC_EDGEHEIGHT_EDIT             1028
#define IDC_EDGEHEIGHT_SPIN             1029
#define IDC_OFFSET_EDIT                 1030
#define IDC_OFFSET_SPIN                 1031
#define IDC_ENABLE                      1032
#define IDC_OFFSET2_EDIT                1032
#define IDC_OFFSET2_SPIN                1033
#define IDC_MAP1                        1033
#define IDC_RAND_OBJ                    1033
#define IDC_MAP2                        1034
#define IDC_RAND_PAR                    1034
#define IDC_MAP3                        1035
#define IDC_RAND_TILE                   1035
#define IDC_MAP4                        1036
#define IDC_DISTORTION_TE2              1036
#define IDC_TILEWIDTH_EDIT2             1036
#define IDC_ROTUV                       1037
#define IDC_MAP5                        1037
#define IDC_MAP6                        1038
#define IDC_VAR_TYPE                    1038
#define IDC_TILEHEIGHT_EDIT2            1038
#define IDC_MAP7                        1039
#define IDC_AUTO                        1039
#define IDC_MAP8                        1040
#define IDC_GRADIENT                    1040
#define IDC_EDGEWIDTH_EDIT2             1040
#define IDC_MAP9                        1041
#define IDC_EDGEHEIGHT_EDIT2            1041
#define IDC_MAP10                       1042
#define IDC_EDGEHEIGHT_SPIN2            1042
#define IDC_MAP11                       1043
#define IDC_TILEWIDTH_SPIN2             1043
#define IDC_MAP12                       1044
#define IDC_KEYTEX                      1044
#define IDC_TILEHEIGHT_SPIN2            1044
#define IDC_MAP13                       1045
#define IDC_KEYCOL                      1045
#define IDC_EDGEWIDTH_SPIN2             1045
#define IDC_MAP14                       1046
#define IDC_KEYPOS_EDIT                 1046
#define IDC_NOISE_COL1                  1047
#define IDC_MAP15                       1047
#define IDC_KEYPOS_SPIN                 1047
#define IDC_NOISE_COL2                  1048
#define IDC_MAP16                       1048
#define IDC_KEYNUM_EDIT                 1048
#define IDC_NOISESIZE_SPIN              1049
#define IDC_NOISE_COL3                  1049
#define IDC_KEYNUM_SPIN                 1049
#define IDC_NOISESIZE_EDIT              1050
#define IDC_GRADIENT_TYPE               1050
#define IDS_DS_COLOR1                   1051
#define IDC_NOISE_TEX1                  1051
#define IDC_RAND_MAT                    1051
#define IDS_DS_COLOR2                   1052
#define IDC_NOISE_TEX2                  1052
#define IDC_RANGEMIN_SPIN               1052
#define IDS_JW_MAP1                     1053
#define IDC_DISTORTION_TEX              1053
#define IDC_RANGEMAX_SPIN               1053
#define IDC_OFF_Y                       1053
#define IDS_JW_MAP2                     1054
#define IDC_NOISE_TEX3                  1054
#define IDC_GRADIENT_INT                1054
#define IDC_OFF_Y_SPIN                  1054
#define IDS_JW_MAP1ENABLE               1055
#define IDC_NOISEPHASE_EDIT             1055
#define IDC_DISTORTION_TEX2             1055
#define IDC_IOR_SPIN                    1055
#define IDC_SIZ_X                       1055
#define IDS_JW_MAP2ENABLE               1056
#define IDC_NOISEPHASE_SPIN             1056
#define IDC_LOCKEDGE                    1056
#define IDC_MAPTEX                      1056
#define IDC_SIZ_X_SPIN                  1056
#define IDS_DS_NOISESIZE                1057
#define IDC_NOISELEV_EDIT               1057
#define IDC_WIDTHVAR_EDIT               1057
#define IDC_VAR_MAP                     1057
#define IDC_NODE                        1057
#define IDC_ANG_X                       1057
#define IDS_DS_PHASE                    1058
#define IDC_NOISELEV_SPIN               1058
#define IDC_WIDTHVAR_SPIN               1058
#define IDC_UV_MAP                      1058
#define IDC_GRADIENT_UVW                1058
#define IDC_ANG_X_SPIN                  1058
#define IDS_DS_NSLEV                    1059
#define IDC_WORLEY_EDIT                 1059
#define IDC_TRESHLOW_EDIT               1059
#define IDC_MATIDFROM_EDIT              1059
#define IDC_GRADIENT_NORMAL             1059
#define IDC_SIZ_Y                       1059
#define IDC_PATTERN                     1059
#define IDS_RB_LOWTHRESH                1060
#define IDC_WORLEY_SPIN                 1060
#define IDC_TRESHLOW_SPIN               1060
#define IDC_MATIDFROM_SPIN              1060
#define IDC_GRADIENT_NORMAL2            1060
#define IDC_SIZ_Y_SPIN                  1060
#define IDS_RB_HIGHTHRESH               1061
#define IDC_TRESHHIGH_EDIT              1061
#define IDC_MATIDTO_EDIT                1061
#define IDC_DISTEX                      1061
#define IDC_ANG_Y                       1061
#define IDS_NOISE_TYPE                  1062
#define IDC_TRESHHIGH_SPIN              1062
#define IDC_MATIDTO_SPIN                1062
#define IDC_DISTSTR_SPIN                1062
#define IDC_ANG_Y_SPIN                  1062
#define IDS_NOISE_FUNCTION              1063
#define IDC_DISTORTION_EDIT             1063
#define IDC_DISTON                      1063
#define IDC_OFF_Z                       1063
#define IDS_NF_OLD                      1064
#define IDC_DISTORTION_SPIN             1064
#define IDC_OFF_Z_SPIN                  1064
#define IDS_NF_NEW                      1065
#define IDC_GAINVAR_EDIT                1065
#define IDC_VAR_STR_EDIT                1065
#define IDC_F1_EDIT                     1065
#define IDC_TIL_X                       1065
#define IDS_NF_SIMPLEX                  1066
#define IDC_GAINVAR_SPIN                1066
#define IDC_VAR_STR_SPIN                1066
#define IDC_F1_SPIN                     1066
#define IDC_TIL_Y                       1066
#define IDS_NF_SIMPLEX2                 1066
#define IDS_OUTPUT_NOISE                1067
#define IDC_PERIOD_EDIT                 1067
#define IDC_F2_EDIT                     1067
#define IDC_SAMPLES_EDIT                1067
#define IDC_SIZ_Z                       1067
#define IDS_WORLEY_DISTANCE             1068
#define IDC_PERIOD_SPIN                 1068
#define IDC_F2_SPIN                     1068
#define IDC_SAMPLES_SPIN                1068
#define IDC_SIZ_Z_SPIN                  1068
#define IDS_FRACTAL_TYPE                1069
#define IDC_SOFTENRAD_EDIT              1069
#define IDC_F3_EDIT                     1069
#define IDC_ANG_Z                       1069
#define IDS_WORLEY_SPREAD               1070
#define IDC_SOFTENRAD_SPIN              1070
#define IDC_F3_SPIN                     1070
#define IDC_ANG_Z_SPIN                  1070
#define IDS_W_LIN                       1071
#define IDC_CORNER_EDIT                 1071
#define IDC_F4_EDIT                     1071
#define IDC_TIL_Z                       1071
#define IDS_W_SQU                       1072
#define IDC_CORNER_SPIN                 1072
#define IDC_F4_SPIN                     1072
#define IDC_OFF_X                       1072
#define IDS_W_MAN                       1073
#define IDC_SKEW_EDIT                   1073
#define IDC_UVCHAN_EDIT                 1073
#define IDC_OFF_X_SPIN                  1073
#define IDS_W_CHE                       1074
#define IDC_SKEW_SPIN                   1074
#define IDC_UVCHAN_SPIN                 1074
#define IDC_FILTER                      1074
#define IDC_UVCHAN_EDIT2                1075
#define IDC_OFF_Z_SPIN3                 1075
#define IDC_FILTER_SPIN                 1075
#define IDC_UVCHAN_SPIN2                1076
#define IDC_REVERSE                     1076
#define IDC_UVCHAN_EDIT3                1077
#define IDC_RANGELOOP                   1077
#define IDC_UVCHAN_SPIN3                1078
#define IDC_FLIPX                       1078
#define IDC_RADIALSTR_EDIT              1080
#define IDC_RADIALSTR_SPIN              1081
#define IDC_RADIALFREQ_EDIT             1082
#define IDC_RADIALFREQ_SPIN             1083
#define IDC_ANGLESTR_EDIT               1084
#define IDC_ANGLESTR_SPIN               1085
#define IDC_ANGLEFREQ_EDIT              1086
#define IDC_ANGLEFREQ_SPIN              1087
#define IDC_RADIALZ_EDIT                1088
#define IDC_RADIALZ_SPIN                1089
#define IDC_GRAINSTR_EDIT               1090
#define IDC_GRAINSTR_SPIN               1091
#define IDC_GRAINFREQ_EDIT              1092
#define IDC_GRAINFREQ_SPIN              1093
#define IDC_RAND_MAT2                   1093
#define IDC_ANGLERAD_EDIT               1094
#define IDC_OFF_X2                      1094
#define IDC_ANGLERAD_SPIN               1095
#define IDC_OFF_X_SPIN2                 1095
#define IDC_SIZ_X2                      1096
#define IDC_SIZ_X_SPIN2                 1097
#define IDC_ANG_X2                      1098
#define IDC_ANG_X_SPIN2                 1099
#define IDC_OFF_Y2                      1101
#define IDC_OFF_Y_SPIN2                 1102
#define IDC_SIZ_Y2                      1103
#define IDC_SIZ_Y_SPIN2                 1104
#define IDC_ANG_Y2                      1105
#define IDC_RANDROT                     1105
#define IDC_ANG_Y_SPIN2                 1106
#define IDC_RANDROT_SPIN                1106
#define IDC_OFF_Z2                      1108
#define IDC_OFF_Z_SPIN2                 1109
#define IDC_SIZ_Z2                      1110
#define IDC_SIZ_Z_SPIN2                 1111
#define IDC_ANG_Z2                      1112
#define IDC_ANG_Z_SPIN2                 1113
#define IDC_LOCK                        1115
#define IDC_COLOR                       1456
#define IDC_EDIT                        1490
#define IDC_AGAMMA_EDIT                 1490
#define IDC_AHUE_EDIT                   1491
#define IDC_ASAT_EDIT                   1492
#define IDC_RGAMMA_EDIT                 1493
#define IDC_RHUE_EDIT                   1494
#define IDC_RSAT_EDIT                   1495
#define IDC_SPIN                        1496
#define IDC_AGAMMA_SPIN                 1496
#define IDC_AHUE_SPIN                   1497
#define IDC_ASAT_SPIN                   1498
#define IDC_RGAMMA_SPIN                 1499
#define IDC_RHUE_SPIN                   1500
#define IDC_RSAT_SPIN                   1501
#define IDC_OGAMMA_EDIT                 1502
#define IDC_OGAMMA_SPIN                 1503
#define IDC_OHUE_EDIT                   1504
#define IDC_OHUE_SPIN                   1505
#define IDC_NOISE_LOWTHRESH             1506
#define IDC_OSAT_EDIT                   1506
#define IDC_NOISE_LOWTHRESHSPIN         1507
#define IDC_OSAT_SPIN                   1507
#define IDC_NOISE_HIGHTHRESH            1508
#define IDC_NOISE_HIGHTHRESHSPIN        1509
#define IDC_FRACTAL_OFFSET_EDIT         1510
#define IDC_CHAN                        1510
#define IDC_BLUR_EDIT                   1510
#define IDC_FRACTAL_OFFSET_SPIN         1511
#define IDC_CHAN_SPIN                   1511
#define IDC_BLUR_SPIN                   1511
#define IDC_FRACTAL_GAIN_EDIT           1512
#define IDC_FRACTAL_GAIN_SPIN           1513
#define IDC_FRACTAL_LACUNARITY_EDIT     1514
#define IDC_FRACTAL_LACUNARITY_SPIN     1515
#define IDC_FRACTAL_H_EDIT              1516
#define IDC_FRACTAL_H_SPIN              1517
#define IDC_MAPON1                      1640
#define IDC_MAPON2                      1641
#define IDC_MAPON4                      1642
#define IDC_USE_DISTORTION              1643
#define IDC_MAPON5                      1643
#define IDC_MAPON3                      1644
#define IDC_SOLID_WORLEY                1644
#define IDC_MAPON6                      1645
#define IDC_LOCK_GRAIN                  1646
#define IDC_MAPON7                      1646
#define IDC_CORNERS                     1647
#define IDC_MAPON8                      1647
#define IDC_MAPUV                       1648
#define IDC_MAPON9                      1648
#define IDC_MAPON10                     1649
#define IDC_MAPUV2                      1649
#define IDC_MATIDON                     1649
#define IDC_MAPON11                     1650
#define IDC_MAPUV3                      1650
#define IDC_MAPON12                     1651
#define IDC_FLIPY                       1651
#define IDC_MAPON13                     1652
#define IDC_MAPON14                     1653
#define IDC_RANDZ                       1653
#define IDC_MAPON15                     1654
#define IDC_MAPON16                     1655
#define ID_ADDKEY                       40001
#define ID_ADDKEY_ADDKEY                40002
#define ID_ADDKEY_REMOVEKEY             40003
#define ID_MENU_RESET                   40004
#define ID_MENU_REMOVEKEY               40005
#define ID_MENU_ADDKEY                  40006
#define ID_RESET_RESET                  40007
#define ID_MENU_                        40008
#define ID_HELP_ALT                     40009

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        248
#define _APS_NEXT_COMMAND_VALUE         40010
#define _APS_NEXT_CONTROL_VALUE         1079
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
