//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by BerconNoise.rc
//
#define IDR_GRADIENTMENU                101
#define IDB_BITMAPLOGO                  102
#define IDD_PANEL                       103
#define IDD_PANEL_COLOR                 104
#define IDD_PANEL_CURVE                 105
#define IDD_PANEL_DISTORTION            106
#define IDD_PANEL_MULTI                 107
#define IDD_PANEL_NOISE_MAP             108
#define IDD_PANEL_TILE                  109
#define IDD_PANEL_TILE1                 110
#define IDD_PANEL_TILE2                 111
#define IDD_PANEL_TILE3                 112
#define IDD_PANEL_TILE_MAP              113
#define IDD_PANEL_WOOD                  114
#define IDD_PANEL_WOOD_MAP              115
#define IDD_XYZ                         116
#define IDS_AGAMMA2                     200
#define IDS_AHUE2                       201
#define IDS_ANGLEFREQ                   202
#define IDS_ANGLERAD                    203
#define IDS_ANGLESTR                    204
#define IDS_ASAT                        205
#define IDS_BERCON_COLOR                206
#define IDS_BERCON_DIST                 207
#define IDS_BERCON_TILE                 208
#define IDS_BERCON_WOOD                 209
#define IDS_BLUR2                       210
#define IDS_CATEGORY                    211
#define IDS_CENTER_MAP                  212
#define IDS_CLASS_NAME                  213
#define IDS_CLASS_NAME_MULTI            214
#define IDS_COORDS                      215
#define IDS_CURVE                       216
#define IDS_CURVEPARM                   217
#define IDS_CURVEPB                     218
#define IDS_DISTON                      219
#define IDS_DISTORTION_MAP              220
#define IDS_DISTORTION_MAP2             221
#define IDS_DISTORTION_STRENGTH         222
#define IDS_DIST_UVW                    223
#define IDS_DS_COLOR1                   224
#define IDS_DS_COLOR2                   225
#define IDS_DS_COLOR3                   226
#define IDS_DS_NOISESIZE                227
#define IDS_DS_NSLEV                    228
#define IDS_DS_PHASE                    229
#define IDS_FILTERING2                  230
#define IDS_FLIP_X                      231
#define IDS_FLIP_Y                      232
#define IDS_FRACTAL_GAIN                233
#define IDS_FRACTAL_H                   234
#define IDS_FRACTAL_LACUNARITY          235
#define IDS_FRACTAL_OFFSET              236
#define IDS_FRACTAL_TYPE                237
#define IDS_F_FBM                       238
#define IDS_F_FBMTURB                   239
#define IDS_F_FRACTAL                   240
#define IDS_F_HETEROTERRAIN             241
#define IDS_F_HYBRIDMULTIFRACTAL        242
#define IDS_F_REGULAR                   243
#define IDS_F_RIDGEDMULTIFRACTAL        244
#define IDS_F_TURBULENCE                245
#define IDS_GAINVAR                     246
#define IDS_GRADIENTINTERPOLATION       247
#define IDS_GRADIENTTYPE                248
#define IDS_GRADIENTUVW                 249
#define IDS_GRADINT_LINEAR              250
#define IDS_GRADINT_SMOOTH              251
#define IDS_GRADINT_SOLIDLEFT           252
#define IDS_GRADINT_SOLIDNEAR           253
#define IDS_GRADINT_SOLIDRIGHT          254
#define IDS_GRADTYPE_AGE                255
#define IDS_GRADTYPE_DISTANCE           256
#define IDS_GRADTYPE_LIGHT              257
#define IDS_GRADTYPE_MAP                258
#define IDS_GRADTYPE_NORMAL             259
#define IDS_GRADTYPE_RANDOM             260
#define IDS_GRADTYPE_SIZE               261
#define IDS_GRADTYPE_SPEED              262
#define IDS_GRADTYPE_UVW                263
#define IDS_GRADUVW_BOX                 264
#define IDS_GRADUVW_DIAGONAL            265
#define IDS_GRADUVW_LINEAR              266
#define IDS_GRADUVW_PONG                267
#define IDS_GRADUVW_RADIAL              268
#define IDS_GRADUVW_RECTANGLE           269
#define IDS_GRADUVW_SPHERICAL           270
#define IDS_GRADUVW_SPIRAL              271
#define IDS_GRADUVW_SWEEP               272
#define IDS_GRADUVW_TARTAN              273
#define IDS_GRAINFREQ                   274
#define IDS_GRAINSTR                    275
#define IDS_IOR                         276
#define IDS_JW_MAP1                     277
#define IDS_JW_MAP1ENABLE               278
#define IDS_JW_MAP2                     279
#define IDS_JW_MAP2ENABLE               280
#define IDS_JW_MAP3                     281
#define IDS_JW_MAP3ENABLE               282
#define IDS_KEYCOL                      283
#define IDS_KEYNUM                      284
#define IDS_KEYPOS                      285
#define IDS_KEYTEX                      286
#define IDS_LIBDESCRIPTION              287
#define IDS_LINEAR_WOOD                 288
#define IDS_LOCK_GRAIN                  289
#define IDS_LOCK_SCALE                  290
#define IDS_LOOP_CONT                   291
#define IDS_LOOP_MIRROR                 292
#define IDS_LOOP_NONE                   293
#define IDS_LOOP_STRETCH                294
#define IDS_LOOP_TILE                   295
#define IDS_MAP                         296
#define IDS_MAP1                        297
#define IDS_MAP10                       298
#define IDS_MAP11                       299
#define IDS_MAP12                       300
#define IDS_MAP13                       301
#define IDS_MAP14                       302
#define IDS_MAP15                       303
#define IDS_MAP16                       304
#define IDS_MAP2                        305
#define IDS_MAP3                        306
#define IDS_MAP4                        307
#define IDS_MAP5                        308
#define IDS_MAP6                        309
#define IDS_MAP7                        310
#define IDS_MAP8                        311
#define IDS_MAP9                        312
#define IDS_MAPON1                      313
#define IDS_MAPON10                     314
#define IDS_MAPON11                     315
#define IDS_MAPON12                     316
#define IDS_MAPON13                     317
#define IDS_MAPON14                     318
#define IDS_MAPON15                     319
#define IDS_MAPON16                     320
#define IDS_MAPON2                      321
#define IDS_MAPON3                      322
#define IDS_MAPON4                      323
#define IDS_MAPON5                      324
#define IDS_MAPON6                      325
#define IDS_MAPON7                      326
#define IDS_MAPON8                      327
#define IDS_MAPON9                      328
#define IDS_NF_PERLIN2                  329
#define IDS_NF_PERLIN3                  330
#define IDS_NF_PERLIN4                  331
#define IDS_NF_SIMPLEX2                 332
#define IDS_NF_SIMPLEX3                 333
#define IDS_NF_SIMPLEX4                 334
#define IDS_NF_WORLEY                   335
#define IDS_NODE                        336
#define IDS_NOISE_FUNCTION              337
#define IDS_NOISE_TYPE                  338
#define IDS_NORMALFUNCTION              339
#define IDS_NORMALTYPE                  340
#define IDS_NORMAL_CAMERAX              341
#define IDS_NORMAL_CAMERAY              342
#define IDS_NORMAL_CAMERAZ              343
#define IDS_NORMAL_FRESNEL              344
#define IDS_NORMAL_LOCALX               345
#define IDS_NORMAL_LOCALY               346
#define IDS_NORMAL_LOCALZ               347
#define IDS_NORMAL_OBJECTZ              348
#define IDS_NORMAL_PARALLEL             349
#define IDS_NORMAL_TOOBJECT             350
#define IDS_NORMAL_TOWARDS              351
#define IDS_NORMAL_VIEW                 352
#define IDS_NORMAL_WORLDX               353
#define IDS_NORMAL_WORLDY               354
#define IDS_NORMAL_WORLDZ               355
#define IDS_OGAMMA2                     356
#define IDS_OHUE2                       357
#define IDS_OSAT2                       358
#define IDS_OUTPUT                      359
#define IDS_OUTPUT_NOISE                360
#define IDS_PARAMS                      361
#define IDS_PATTERN_STRING              362
#define IDS_PBMAP                       363
#define IDS_PERLIN_WOOD                 364
#define IDS_RADIALFREQ                  365
#define IDS_RADIALSTR                   366
#define IDS_RADIALZ                     367
#define IDS_RADIAL_WOOD                 368
#define IDS_RANDBYMAT                   369
#define IDS_RANDBYOBJ                   370
#define IDS_RANDBYPAR                   371
#define IDS_RANDOM_X_OFF                372
#define IDS_RANDOM_X_SCA                373
#define IDS_RANDOM_Y_OFF                374
#define IDS_RANDOM_Y_SCA                375
#define IDS_RANGELOOP                   376
#define IDS_RANGEMAX                    377
#define IDS_RANGEMIN                    378
#define IDS_RB_HIGHTHRESH               379
#define IDS_RB_LOWTHRESH                380
#define IDS_REVERSE                     381
#define IDS_RGAMMA2                     382
#define IDS_RHUE2                       383
#define IDS_RNDBY2                      384
#define IDS_RSAT2                       385
#define IDS_SAMPLES                     386
#define IDS_SEED                        387
#define IDS_SIMPLEX_WOOD                388
#define IDS_SKEW                        389
#define IDS_STRING262                   390
#define IDS_SUBCOLORS                   391
#define IDS_SUBMAPS                     392
#define IDS_SUBPOSITIONS                393
#define IDS_SUPPORT                     394
#define IDS_TILEROT_0                   395
#define IDS_TILEROT_1                   396
#define IDS_TILEROT_2                   397
#define IDS_TILEROT_3                   398
#define IDS_TILEROT_4                   399
#define IDS_TILESOFTEN_0                400
#define IDS_TILESOFTEN_1                401
#define IDS_TILESOFTEN_2                402
#define IDS_TILESOFTEN_3                403
#define IDS_TILETYPE_0                  404
#define IDS_TILETYPE_1                  405
#define IDS_TILETYPE_10                 406
#define IDS_TILETYPE_11                 407
#define IDS_TILETYPE_2                  408
#define IDS_TILETYPE_3                  409
#define IDS_TILETYPE_4                  410
#define IDS_TILETYPE_5                  411
#define IDS_TILETYPE_6                  412
#define IDS_TILETYPE_7                  413
#define IDS_TILETYPE_8                  414
#define IDS_TILETYPE_9                  415
#define IDS_TILEUVW_0                   416
#define IDS_TILEUVW_1                   417
#define IDS_TILEUVW_2                   418
#define IDS_TILEUVW_3                   419
#define IDS_TILEUVW_4                   420
#define IDS_TILEUVW_5                   421
#define IDS_TILEVAR_0                   422
#define IDS_TILEVAR_1                   423
#define IDS_TILEVAR_2                   424
#define IDS_TILE_AUTO                   425
#define IDS_TILE_EHEIGHT                426
#define IDS_TILE_EHEIGHT2               427
#define IDS_TILE_EWIDTH                 428
#define IDS_TILE_EWIDTH2                429
#define IDS_TILE_HEIGHT                 430
#define IDS_TILE_HEIGHT2                431
#define IDS_TILE_LOCK                   432
#define IDS_TILE_MAPUV                  433
#define IDS_TILE_OFFSET                 434
#define IDS_TILE_OFFSET2                435
#define IDS_TILE_PERIOD                 436
#define IDS_TILE_ROT                    437
#define IDS_TILE_ROTUV                  438
#define IDS_TILE_ROUND                  439
#define IDS_TILE_ROUNDRAD               440
#define IDS_TILE_SIZE                   441
#define IDS_TILE_SOFTEN                 442
#define IDS_TILE_SOFTRAD                443
#define IDS_TILE_STYLE                  444
#define IDS_TILE_WIDTH                  445
#define IDS_TILE_WIDTH2                 446
#define IDS_TILING                      447
#define IDS_TILINGSIZE                  448
#define IDS_TRUNKFREQ                   449
#define IDS_TRUNKSTR                    450
#define IDS_ULOOP                       451
#define IDS_USE_DISTORTION              452
#define IDS_UVWCHAN                     453
#define IDS_UVWCHAN2                    454
#define IDS_UVW_NORMAL                  455
#define IDS_UVW_RADIAL                  456
#define IDS_UVW_SPHERICAL               457
#define IDS_UV_MAP                      458
#define IDS_VAR_MAP                     459
#define IDS_VAR_STR                     460
#define IDS_VAR_TYPE                    461
#define IDS_VLOOP                       462
#define IDS_WIDTHVAR                    463
#define IDS_WLOOP                       464
#define IDS_WOODSIZE                    465
#define IDS_WOOD_TYPE                   466
#define IDS_WORLEY_DISTANCE             467
#define IDS_WORLEY_F1                   468
#define IDS_WORLEY_F2                   469
#define IDS_WORLEY_F3                   470
#define IDS_WORLEY_F4                   471
#define IDS_WORLEY_SPREAD               472
#define IDS_W_CHE                       473
#define IDS_W_ID                        474
#define IDS_W_LIN                       475
#define IDS_W_MAN                       476
#define IDS_W_MI4                       477
#define IDS_W_MI5                       478
#define IDS_W_SQU                       479
#define IDS_XYZ                         480
#define IDS_XYZ_OBJ                     481
#define IDS_XYZ_SCR                     482
#define IDS_XYZ_UVW                     483
#define IDS_XYZ_UVW2                    484
#define IDS_XYZ_WOR                     485
#define IDS_XYZ_OFFSET_X                486
#define IDS_XYZ_OFFSET_Y                487
#define IDS_XYZ_OFFSET_Z                488
#define IDC_AGAMMA_EDIT                 1001
#define IDC_AGAMMA_SPIN                 1002
#define IDC_AHUE_EDIT                   1003
#define IDC_AHUE_SPIN                   1004
#define IDC_ANGLEFREQ_EDIT              1005
#define IDC_ANGLEFREQ_SPIN              1006
#define IDC_ANGLERAD_EDIT               1007
#define IDC_ANGLERAD_SPIN               1008
#define IDC_ANGLESTR_EDIT               1009
#define IDC_ANGLESTR_SPIN               1010
#define IDC_ANG_X                       1011
#define IDC_ANG_X2                      1012
#define IDC_ANG_X_SPIN                  1013
#define IDC_ANG_X_SPIN2                 1014
#define IDC_ANG_Y                       1015
#define IDC_ANG_Y2                      1016
#define IDC_ANG_Y_SPIN                  1017
#define IDC_ANG_Y_SPIN2                 1018
#define IDC_ANG_Z                       1019
#define IDC_ANG_Z2                      1020
#define IDC_ANG_Z_SPIN                  1021
#define IDC_ANG_Z_SPIN2                 1022
#define IDC_ASAT_EDIT                   1023
#define IDC_ASAT_SPIN                   1024
#define IDC_AUTO                        1025
#define IDC_BLUR_EDIT                   1026
#define IDC_BLUR_SPIN                   1027
#define IDC_CHAN                        1028
#define IDC_CHAN_SPIN                   1029
#define IDC_CORNERS                     1030
#define IDC_CORNER_EDIT                 1031
#define IDC_CORNER_SPIN                 1032
#define IDC_CURVE                       1033
#define IDC_DISTEX                      1034
#define IDC_DISTON                      1035
#define IDC_DISTORTION_EDIT             1036
#define IDC_DISTORTION_SPIN             1037
#define IDC_DISTORTION_TE2              1038
#define IDC_DISTORTION_TEX              1039
#define IDC_DISTORTION_TEX2             1040
#define IDC_DISTSTR_EDIT                1041
#define IDC_DISTSTR_SPIN                1042
#define IDC_DIST_UVW                    1043
#define IDC_EDGEHEIGHT_EDIT             1044
#define IDC_EDGEHEIGHT_EDIT2            1045
#define IDC_EDGEHEIGHT_SPIN             1046
#define IDC_EDGEHEIGHT_SPIN2            1047
#define IDC_EDGEWIDTH_EDIT              1048
#define IDC_EDGEWIDTH_EDIT2             1049
#define IDC_EDGEWIDTH_SPIN              1050
#define IDC_EDGEWIDTH_SPIN2             1051
#define IDC_ENABLE                      1052
#define IDC_F1_EDIT                     1053
#define IDC_F1_SPIN                     1054
#define IDC_F2_EDIT                     1055
#define IDC_F2_SPIN                     1056
#define IDC_F3_EDIT                     1057
#define IDC_F3_SPIN                     1058
#define IDC_F4_EDIT                     1059
#define IDC_F4_SPIN                     1060
#define IDC_FILTER                      1061
#define IDC_FILTERING_1                 1062
#define IDC_FILTERING_2                 1063
#define IDC_FILTERING_3                 1064
#define IDC_FILTER_SPIN                 1065
#define IDC_FLIPX                       1066
#define IDC_FLIPY                       1067
#define IDC_FRACTAL_GAIN_EDIT           1068
#define IDC_FRACTAL_GAIN_SPIN           1069
#define IDC_FRACTAL_H_EDIT              1070
#define IDC_FRACTAL_H_SPIN              1071
#define IDC_FRACTAL_LACUNARITY_EDIT     1072
#define IDC_FRACTAL_LACUNARITY_SPIN     1073
#define IDC_FRACTAL_OFFSET_EDIT         1074
#define IDC_FRACTAL_OFFSET_SPIN         1075
#define IDC_FRACTAL_TYPE                1076
#define IDC_GAINVAR_EDIT                1077
#define IDC_GAINVAR_SPIN                1078
#define IDC_GRADIENT                    1079
#define IDC_GRADIENT_INT                1080
#define IDC_GRADIENT_NORMAL             1081
#define IDC_GRADIENT_NORMAL2            1082
#define IDC_GRADIENT_TYPE               1083
#define IDC_GRADIENT_UVW                1084
#define IDC_GRAINFREQ_EDIT              1085
#define IDC_GRAINFREQ_SPIN              1086
#define IDC_GRAINSTR_EDIT               1087
#define IDC_GRAINSTR_SPIN               1088
#define IDC_IOR_EDIT                    1089
#define IDC_IOR_SPIN                    1090
#define IDC_KEYCOL                      1091
#define IDC_KEYNUM_EDIT                 1092
#define IDC_KEYNUM_SPIN                 1093
#define IDC_KEYPOS_EDIT                 1094
#define IDC_KEYPOS_SPIN                 1095
#define IDC_KEYTEX                      1096
#define IDC_LOCK                        1097
#define IDC_LOCKEDGE                    1098
#define IDC_LOCK_GRAIN                  1099
#define IDC_LOGO                        1100
#define IDC_MAP1                        1101
#define IDC_MAP10                       1102
#define IDC_MAP11                       1103
#define IDC_MAP12                       1104
#define IDC_MAP13                       1105
#define IDC_MAP14                       1106
#define IDC_MAP15                       1107
#define IDC_MAP16                       1108
#define IDC_MAP2                        1109
#define IDC_MAP3                        1110
#define IDC_MAP4                        1111
#define IDC_MAP5                        1112
#define IDC_MAP6                        1113
#define IDC_MAP7                        1114
#define IDC_MAP8                        1115
#define IDC_MAP9                        1116
#define IDC_MAPON1                      1117
#define IDC_MAPON10                     1118
#define IDC_MAPON11                     1119
#define IDC_MAPON12                     1120
#define IDC_MAPON13                     1121
#define IDC_MAPON14                     1122
#define IDC_MAPON15                     1123
#define IDC_MAPON16                     1124
#define IDC_MAPON2                      1125
#define IDC_MAPON3                      1126
#define IDC_MAPON4                      1127
#define IDC_MAPON5                      1128
#define IDC_MAPON6                      1129
#define IDC_MAPON7                      1130
#define IDC_MAPON8                      1131
#define IDC_MAPON9                      1132
#define IDC_MAPTEX                      1133
#define IDC_MAPUV                       1134
#define IDC_MAPUV2                      1135
#define IDC_MAPUV3                      1136
#define IDC_MATIDFROM_EDIT              1137
#define IDC_MATIDFROM_SPIN              1138
#define IDC_MATIDON                     1139
#define IDC_MATIDTO_EDIT                1140
#define IDC_MATIDTO_SPIN                1141
#define IDC_NODE                        1142
#define IDC_NOISELEV_EDIT               1143
#define IDC_NOISELEV_SPIN               1144
#define IDC_NOISEPHASE_EDIT             1145
#define IDC_NOISEPHASE_SPIN             1146
#define IDC_NOISESIZE_EDIT              1147
#define IDC_NOISESIZE_SPIN              1148
#define IDC_NOISE_COL1                  1149
#define IDC_NOISE_COL2                  1150
#define IDC_NOISE_COL3                  1151
#define IDC_NOISE_FUNCTION              1152
#define IDC_NOISE_HIGHTHRESH            1153
#define IDC_NOISE_HIGHTHRESHSPIN        1154
#define IDC_NOISE_LOWTHRESH             1155
#define IDC_NOISE_LOWTHRESHSPIN         1156
#define IDC_NOISE_TEX1                  1157
#define IDC_NOISE_TEX2                  1158
#define IDC_NOISE_TEX3                  1159
#define IDC_OFFSET2_EDIT                1160
#define IDC_OFFSET2_SPIN                1161
#define IDC_OFFSET_EDIT                 1162
#define IDC_OFFSET_SPIN                 1163
#define IDC_OFF_X                       1164
#define IDC_OFF_X2                      1165
#define IDC_OFF_X_SPIN                  1166
#define IDC_OFF_X_SPIN2                 1167
#define IDC_OFF_Y                       1168
#define IDC_OFF_Y2                      1169
#define IDC_OFF_Y_SPIN                  1170
#define IDC_OFF_Y_SPIN2                 1171
#define IDC_OFF_Z                       1172
#define IDC_OFF_Z2                      1173
#define IDC_OFF_Z_SPIN                  1174
#define IDC_OFF_Z_SPIN2                 1175
#define IDC_OGAMMA_EDIT                 1176
#define IDC_OGAMMA_SPIN                 1177
#define IDC_OHUE_EDIT                   1178
#define IDC_OHUE_SPIN                   1179
#define IDC_OPENBUTTON                  1180
#define IDC_OSAT_EDIT                   1181
#define IDC_OSAT_SPIN                   1182
#define IDC_PATTERN                     1183
#define IDC_PERIOD_EDIT                 1184
#define IDC_PERIOD_SPIN                 1185
#define IDC_RADIALFREQ_EDIT             1186
#define IDC_RADIALFREQ_SPIN             1187
#define IDC_RADIALSTR_EDIT              1188
#define IDC_RADIALSTR_SPIN              1189
#define IDC_RADIALZ_EDIT                1190
#define IDC_RADIALZ_SPIN                1191
#define IDC_RANDROT                     1192
#define IDC_RANDROT_SPIN                1193
#define IDC_RANDZ                       1194
#define IDC_RAND_MAT                    1195
#define IDC_RAND_MAT2                   1196
#define IDC_RAND_OBJ                    1197
#define IDC_RAND_PAR                    1198
#define IDC_RAND_TILE                   1199
#define IDC_RANGELOOP                   1200
#define IDC_RANGEMAX_EDIT               1201
#define IDC_RANGEMAX_SPIN               1202
#define IDC_RANGEMIN_EDIT               1203
#define IDC_RANGEMIN_SPIN               1204
#define IDC_RELOADBUTTON                1205
#define IDC_REVERSE                     1206
#define IDC_RGAMMA_EDIT                 1207
#define IDC_RGAMMA_SPIN                 1208
#define IDC_RHUE_EDIT                   1209
#define IDC_RHUE_SPIN                   1210
#define IDC_RNDBY_1                     1211
#define IDC_RNDBY_2                     1212
#define IDC_RNDBY_3                     1213
#define IDC_ROTUV                       1214
#define IDC_RSAT_EDIT                   1215
#define IDC_RSAT_SPIN                   1216
#define IDC_SAMPLES_EDIT                1217
#define IDC_SAMPLES_SPIN                1218
#define IDC_SEED_EDIT                   1219
#define IDC_SEED_SPIN                   1220
#define IDC_SIZ_X                       1221
#define IDS_XYZ_SIZE_X                  1221
#define IDC_SIZ_X2                      1222
#define IDS_XYZ_SIZE_Y                  1222
#define IDC_SIZ_X_SPIN                  1223
#define IDS_XYZ_SIZE_Z                  1223
#define IDC_SIZ_X_SPIN2                 1224
#define IDS_XYZ_ANGLE_X                 1224
#define IDC_SIZ_Y                       1225
#define IDS_XYZ_ANGLE_Y                 1225
#define IDC_SIZ_Y2                      1226
#define IDS_XYZ_ANGLE_Z                 1226
#define IDC_SIZ_Y_SPIN                  1227
#define IDS_XYZ_TILE_X                  1227
#define IDC_SIZ_Y_SPIN2                 1228
#define IDS_XYZ_TILE_Y                  1228
#define IDC_SIZ_Z                       1229
#define IDS_XYZ_TILE_Z                  1229
#define IDC_SIZ_Z2                      1230
#define IDS_XYZ_OFFSET_X2               1230
#define IDC_SIZ_Z_SPIN                  1231
#define IDS_XYZ_OFFSET_Y2               1231
#define IDC_SIZ_Z_SPIN2                 1232
#define IDS_XYZ_OFFSET_Z2               1232
#define IDC_SKEW_EDIT                   1233
#define IDC_SKEW_SPIN                   1234
#define IDC_SOFTEN                      1235
#define IDC_SOFTENRAD_EDIT              1236
#define IDC_SOFTENRAD_SPIN              1237
#define IDC_TILEHEIGHT_EDIT             1238
#define IDC_TILEHEIGHT_EDIT2            1239
#define IDC_TILEHEIGHT_SPIN             1240
#define IDC_TILEHEIGHT_SPIN2            1241
#define IDC_TILESIZE_EDIT               1242
#define IDC_TILESIZE_SPIN               1243
#define IDC_TILEWIDTH_EDIT              1244
#define IDC_TILEWIDTH_EDIT2             1245
#define IDC_TILEWIDTH_SPIN              1246
#define IDC_TILEWIDTH_SPIN2             1247
#define IDC_TIL_X                       1248
#define IDC_TIL_Y                       1249
#define IDC_TIL_Z                       1250
#define IDC_TRESHHIGH_EDIT              1251
#define IDC_TRESHHIGH_SPIN              1252
#define IDC_TRESHLOW_EDIT               1253
#define IDC_TRESHLOW_SPIN               1254
#define IDC_TRUNKFREQ_EDIT              1255
#define IDC_TRUNKFREQ_SPIN              1256
#define IDC_TRUNKSTR_EDIT               1257
#define IDC_TRUNKSTR_SPIN               1258
#define IDC_TYPE                        1259
#define IDC_USE_DISTORTION              1260
#define IDC_UVCHAN_EDIT                 1261
#define IDC_UVCHAN_EDIT2                1262
#define IDC_UVCHAN_EDIT3                1263
#define IDC_UVCHAN_SPIN                 1264
#define IDC_UVCHAN_SPIN2                1265
#define IDC_UVCHAN_SPIN3                1266
#define IDC_UV_MAP                      1267
#define IDC_VAR_MAP                     1268
#define IDC_VAR_STR_EDIT                1269
#define IDC_VAR_STR_SPIN                1270
#define IDC_VAR_TYPE                    1271
#define IDC_WIDTHVAR_EDIT               1272
#define IDC_WIDTHVAR_SPIN               1273
#define IDC_WOODSIZE_EDIT               1274
#define IDC_WOODSIZE_SPIN               1275
#define IDC_WOOD_TYPE                   1276
#define IDC_WORLEY_DISTANCE             1277
#define IDC_WORLEY_EDIT                 1278
#define IDC_WORLEY_SOLID                1279
#define IDC_WORLEY_SPIN                 1280
#define IDS_XYZ_SIZE_X2                 1281
#define IDS_XYZ_SIZE_Y2                 1282
#define IDS_XYZ_SIZE_Z2                 1283
#define IDS_XYZ_ANGLE_X2                1284
#define IDS_XYZ_ANGLE_Y2                1285
#define IDS_XYZ_ANGLE_Z2                1286
#define IDS_XYZ_LOCK                    1287
#define IDS_XYZ_FILTERING               1288
#define ID_HELP_ALT                     32771
#define ID_MENU_ADDKEY                  32772
#define ID_MENU_REMOVEKEY               32773
#define ID_RESET_RESET                  32774

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_3D_CONTROLS                     1
#define _APS_NEXT_RESOURCE_VALUE        486
#define _APS_NEXT_COMMAND_VALUE         32775
#define _APS_NEXT_CONTROL_VALUE         1281
#define _APS_NEXT_SYMED_VALUE           101
#endif
#endif
